name: Snyk Scan

on:
  pull_request:
    branches: [main, test-branch]
    

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Snyk CLI
        run: curl -sSL https://static.snyk.io/cli/latest/snyk-linuxâ€‹ -o /usr/local/bin/snyk && chmod +x /usr/local/bin/snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test
        run: snyk test >> output.txt

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: output.txt


